describe('Enviar dinheiro com saldo suficiente', () => {
  it('Deve enviar dinheiro com sucesso', () => {
    cy.visit('http://localhost:3000/signin')
    cy.get('#username').type('TesteUser')
    cy.get('#password').type('1234')
    cy.get('[data-test="signin-submit"]').click()
    cy.get('[data-test="sidenav-home"] > .MuiListItemText-root > .MuiTypography-root').click()
    cy.get('[data-test="nav-top-new-transaction"]').click()
    cy.get('[data-test="user-list-search-input"]').type('Lia')
    cy.get('[data-test="user-list-item-WHjJ4qR2R2"]').click()
    cy.get('#amount').type('20')
    cy.get('#transaction-create-description-input').type('Transfer test')
    cy.get('[data-test="transaction-create-submit-payment"]').click()
    cy.get('[data-test="alert-bar-success"]').contains('Transaction Submitted!')
  })
})
describe('Enviar dinheiro com saldo insuficiente', () => {
  it('Deve exibir mensagem de erro ao enviar dinheiro sem saldo suficiente', () => {
    cy.visit('http://localhost:3000/signin')
    cy.get('#username').type('TesteUser')
    cy.get('#password').type('1234')
    cy.get('[data-test="signin-submit"]').click()
    cy.get('[data-test="nav-top-new-transaction"]').click()
    cy.get('[data-test="user-list-search-input"]').type('Lia')
    cy.get('[data-test="user-list-item-WHjJ4qR2R2"]').click()
    cy.get('#amount').type('1000')
    cy.get('#transaction-create-description-input').type('Transfer test')
    cy.get('[data-test="transaction-create-submit-payment"]').click()
    y.get('[data-test="alert-bar-success"]').contains('Transaction Submitted!')
  })
})